spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/robertdenilo/eureka_config_file.git
          username: robertdenilo
          password: 
          basedir: F:\workspace\eureka_config_tmp

    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 159.203.21.59
    port: 5672
    username: guest
    password:
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh    #to enable: http://localhost:8080/bus/refresh  curl -v -X POST "http://localhost:8080/actuator/bus-refresh"
debug: true
logging:
  path: F:\workspace\eureka_config_server
